export const zeroConditional1 = [
    {
      id: 1,
      left: "If you mix white and red,",
      leftLoc: undefined,
      right: "it makes pink.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 2,
      left: "When ice melts",
      leftLoc: undefined,
      right: "it becomes water.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 3,
      left: "As long as the lights are red,",
      leftLoc: undefined,
      right: "traffic stops.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 4,
      left: "As soon as my sister eats fish,",
      leftLoc: undefined,
      right: "she is sick.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 5,
      left: "If my son goes to bed late,",
      leftLoc: undefined,
      right: "he cannot wake up at 7.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 6,
      left: "Unless it rains,",
      leftLoc: undefined,
      right: "the plants cannot grow.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 7,
      left: "When you arrive home,",
      leftLoc: undefined,
      right: "call me.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 8,
      left: "When the sun goes down,",
      leftLoc: undefined,
      right: "it gets dark.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 9,
      left: "If you understand,",
      leftLoc: undefined,
      right: "tell me.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 10,
      left: "When you use the zero conditional,",
      leftLoc: undefined,
      right: "the result is true.",
      rightLoc: undefined,
      success: false,
    }
];

export const secondConditional1 = [
    {
      id: 1,
      left: "If I could,",
      leftLoc: undefined,
      right: "I'd fly home.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 2,
      left: "If I won the lottery",
      leftLoc: undefined,
      right: "I'd sail the world.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 3,
      left: "If I was allowed,",
      leftLoc: undefined,
      right: "I'd own a dog.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 4,
      left: "If I knew who did it,",
      leftLoc: undefined,
      right: "I'd report them.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 5,
      left: "If it snowed in Winter,",
      leftLoc: undefined,
      right: "would you go skiing?",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 6,
      left: "If I joined a gym,",
      leftLoc: undefined,
      right: "I would work out more.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 7,
      left: "If I were you,",
      leftLoc: undefined,
      right: "I would go.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 8,
      left: "If we earned more money,",
      leftLoc: undefined,
      right: "we could save more money.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 9,
      left: "If I had caught the bus,",
      leftLoc: undefined,
      right: "I would be home by now.",
      rightLoc: undefined,
      success: false,
    },
    {
      id: 10,
      left: "If you could do any job,",
      leftLoc: undefined,
      right: "which job would you choose?",
      rightLoc: undefined,
      success: false,
    }
];
export const thirdConditional1 = [
  {
    id: 1,
    left: "If I had understood,",
    leftLoc: undefined,
    right: "I wouldn't have made the mistake.",
    rightLoc: undefined,
    success: false,
  },
  {
    id: 2,
    left: "If we had gone another route",
    leftLoc: undefined,
    right: "we would not have got lost.",
    rightLoc: undefined,
    success: false,
  },
  {
    id: 3,
    left: "I wish everyone had helped,",
    leftLoc: undefined,
    right: "then we would already be finished.",
    rightLoc: undefined,
    success: false,
  },
  {
    id: 4,
    left: "If I had had the money,",
    leftLoc: undefined,
    right: "I might have gone on holiday this year.",
    rightLoc: undefined,
    success: false,
  },
  {
    id: 5,
    left: "If you had studied harder,",
    leftLoc: undefined,
    right: "you would have passed the test.",
    rightLoc: undefined,
    success: false,
  },
  {
    id: 6,
    left: "I wish it hadn't rained,",
    leftLoc: undefined,
    right: "so I could have gone out.",
    rightLoc: undefined,
    success: false,
  },
  {
    id: 7,
    left: "If only we had met ealier,",
    leftLoc: undefined,
    right: "we could have spent more time together.",
    rightLoc: undefined,
    success: false,
  },
  {
    id: 8,
    left: "The car driver could have stopped,",
    leftLoc: undefined,
    right: "if she had been paying more attention.",
    rightLoc: undefined,
    success: false,
  },
  {
    id: 9,
    left: "The recipe would have been better,",
    leftLoc: undefined,
    right: "if I had used herbs.",
    rightLoc: undefined,
    success: false,
  },
  {
    id: 10,
    left: "I would have been sad,",
    leftLoc: undefined,
    right: "if you hadn't said hello.",
    rightLoc: undefined,
    success: false,
  }
];
  