import {
  womanThinkingImg,
  secondImg,
  questionMarksImg,
  roadSignPastPresentImg,
  skyWatchOfDinosaurCometImg,
  lettersOutOfBookImg,
  iceBallImg,
  mathsTilesImg,
  malteseImg,
  additionImg,
} from "../functions/staticImgFunctions";

//Menu - [] of {title, img, description, level, link, available lesson links, available exercise links, cluster, mustKnow, next}
export const learningGroups = [
  {
    title: "Past Perfect",
    image: womanThinkingImg(),
    description:
      "All about the past perfect. Learn to talk about a past action before another past action.",
    level: "CEFR B1",
    link: "past-perfect/",
    lessons: ["complete-lesson"],
    exercises: [],
    subcategory: ["tenses"],
    mustKnow: [],
    next: [],
  },
  {
    title: "Second Conditional",
    image: secondImg(),
    description:
      "Learn the conditional for an imagined condition in the present.",
    level: "CEFR B1",
    link: "second-conditional/",
    lessons: ["complete-lesson"],
    exercises: ["exercise-mix-match-1"],
    subcategory: ["conditionals"],
    mustKnow: ["zero-conditional", "first-conditional"],
    next: ["third-conditional"],
  },
  {
    title: "Tag Questions",
    image: questionMarksImg(),
    description:
      "Want to make tiny informal questions to add to the end of a sentence? Here's how!",
    level: "CEFR B1",
    link: "tag-questions/",
    lessons: ["complete-lesson"],
    exercises: [],
    subcategory: [],
    mustKnow: [],
    next: [],
  },
  {
    title: "Tenses",
    image: roadSignPastPresentImg(),
    description:
      "Have a look at the different tenses used in the English language.",
    level: "CEFR B1",
    link: "tenses/",
    lessons: ["overview"],
    exercises: [],
    subcategory: ["tenses"],
    mustKnow: [],
    next: [
      "zero-conditional",
      "first-conditional",
      "second-conditional",
      "third-conditional",
    ],
  },
  {
    title: "Third Conditional",
    image: skyWatchOfDinosaurCometImg(),
    description: "Learn the conditional for an imagined condition in the past.",
    level: "CEFR B2",
    link: "third-conditional/",
    lessons: ["complete-lesson"],
    exercises: ["exercise-mix-match-1"],
    subcategory: ["conditionals"],
    mustKnow: [
      "overview",
      "past-perfect",
      "zero-conditional",
      "first-conditional",
      "second-conditional",
    ],
    next: [],
  },
  {
    title: "Get And Got",
    image: lettersOutOfBookImg(),
    description:
      "Make the use of get and got by native English speakers less confusing.",
    level: "CEFR B1",
    link: "using-get/",
    lessons: ["complete-lesson"],
    exercises: ["exercise-get-for-obtain-1"],
    subcategory: ["tricky-words"],
    mustKnow: [],
    next: [],
  },
  {
    title: "Zero Conditional",
    image: iceBallImg(),
    description: "Learn the conditional for present facts.",
    level: "CEFR A1",
    link: "zero-conditional/",
    lessons: ["complete-lesson"],
    exercises: ["exercise-mix-match-1"],
    subcategory: ["conditionals"],
    mustKnow: [],
    next: ["first-conditional"],
  },
  {
    title: "Times Tables",
    image: mathsTilesImg(),
    description: "Keep practising those times tables from 0 to 12.",
    level: "Primary",
    link: "times-tables/",
    lessons: [],
    exercises: ["simple-exercises-1"],
    subcategory: ["maths"],
    mustKnow: ["addition", "subtraction"],
    next: ["division"],
  },
  {
    title: "Maltese",
    image: malteseImg(),
    description: "Match the Maltese to the English.",
    level: "Primary",
    link: "maltese/",
    lessons: [],
    exercises: ["exercise-mix-match-1"],
    subcategory: ["maltese"],
    mustKnow: [],
    next: [],
  },
  {
    title: "Addition",
    image: additionImg(),
    description: "Practice adding numbers.",
    level: "Primary",
    link: "addition/",
    lessons: [],
    exercises: ["simple-exercises-1"],
    subcategory: ["maths"],
    mustKnow: [],
    next: ["subtraction"],
  },
];
