export const m_animals = {
  lizard: gremxula,
  lion: ljun,
  tiger: tigra,
  worm: dudu,
  elephant: iljunfant,
  chicken: tigiega,
  spider: brimba,
  horse: ziemel,
  cat: qattus,
  dog: kelb,
  crocodile: kukkudrill,
  hippopotamus: ippopotamus,
  bird: ghasfur,
  donkey: hmar,
  pig: hanzir,
  wolf: lupu,
  monkey: xadina,
  parrot: pappagall,
  owl: kokka,
  cockerel: serduq,
  snail: bebbuxu,
  ladybug: nannakola,
  goat: moghza,
  camel: gemel,
  tortoise: fekruna,
  zebra: zebra,
  cow: baqra,
  giraffe: giraffa,
  rabbit: fenek,
  sheep: naghga,
  swan: cinju,
  canary: kanarin,
  pigeon: hamiema,
  robin: pitiross,
  chick: fellus,
  hedgehog: qanfud,
  fish: hut,
};

export const m_house = {
  door: bieb,
  window: tieq,
  room: kamra,
  sodda: bed,
  floor: art,
  kitchen: kcina,
  bath: banju,
  toilet: twalett,
  wall: hajt,
  lights: dwal,
  rug: tapit,
  fridge: frigg,
  shower: docca,
};
